on:
  push:
    tags:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install ssh keys
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: Install dependencies
        run: go mod download
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o bin cmd/tgstat/main.go
      - name: deploy
        run: |
          scp -r migrations ${{ secrets.SERVER }}:/var/www/tgstat/api/
          ssh ${{ secrets.SERVER }} "systemctl stop tgstat-api"
          scp -r bin ${{ secrets.SERVER }}:/var/www/tgstat/api/bin
          ssh ${{ secrets.SERVER }} "chown -R www-data:www-data /var/www/tgstat/api/*"
          ssh ${{ secrets.SERVER }} "systemctl start tgstat-api"